### ISSUE TITLE
运行项目报错，看截图

### ISSUE THREAD

**Issue by kaimengxin** [bailicangdu/vue2-manage#121]
以下内容是报错日志：（本来想截图运行错误的，但是这里放不了图片）还请帮忙指点一下，给你点 星星 了

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue2-manage@1.0.1~predev: vue2-manage@1.0.1
6 info lifecycle vue2-manage@1.0.1~dev: vue2-manage@1.0.1
7 verbose lifecycle vue2-manage@1.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue2-manage@1.0.1~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\vueTest\vue2\node_modules\.bin;C:\Users\Administrator\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\Ruby23-x64\bin;C:\Program Files\ARM\bin\win_32-pentium;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\ARM\RDI\Deprecated\1.3.1\1\windows;C:\Program Files\ARM\RVCT\Programs\3.1\569\win_32-pentium;C:\Program Files\ARM\Utilities\FLEXlm\10.8.5.0\1\win_32-pentium;C:\Program Files\TortoiseSVN\bin;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Local\BypassRuntm;C:\Program Files\nodejs\node_modules;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle vue2-manage@1.0.1~dev: CWD: D:\vueTest\vue2
10 silly lifecycle vue2-manage@1.0.1~dev: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=online node build/dev-server.js' ]
11 silly lifecycle vue2-manage@1.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle vue2-manage@1.0.1~dev: Failed to exec dev script
13 verbose stack Error: vue2-manage@1.0.1 dev: `cross-env NODE_ENV=online node build/dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vue2-manage@1.0.1
15 verbose cwd D:\vueTest\vue2
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error vue2-manage@1.0.1 dev: `cross-env NODE_ENV=online node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue2-manage@1.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by guodonglw** [comment]
先执行rm -r node_models，rm package-lock.json，然后去https://github.com/guodonglw/vue_admin按照我写的东西试一下，看看能不能解决你的问题，能解决的话给我也点个星星啊，哈哈

**Comment by kaimengxin** [comment]
我现在运行线上的没有问题，也就是npm run dev可以。运行 npm run local 报错，登录不了。 config/fitch.js 报错行 ：
export default async(url = '', data = {}, type = 'GET', method = 'fetch') => {

谷歌浏览器错误提示：
Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
2
Uncaught (in promise) Error: SyntaxError: Unexpected token E in JSON at position 0

麻烦告知下原因，谢谢~

**Comment by 944916121** [comment]
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'optimize-css-assets-webpack-plugin'
Require stack:
- c:\Users\FengTingting\Downloads\vue2-manage-master\build\webpack.prod.conf.js
- c:\Users\FengTingting\Downloads\vue2-manage-master\build\build.js
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:681:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:16:16)?[39m
    at Object.<anonymous> (c:\Users\FengTingting\Downloads\vue2-manage-master\build\webpack.prod.conf.js:10:25)
?[90m    at Module._compile (internal/modules/cjs/loader.js:774:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:641:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:681:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:16:16)?[39m
    at Object.<anonymous> (c:\Users\FengTingting\Downloads\vue2-manage-master\build\build.js:11:21)
?[90m    at Module._compile (internal/modules/cjs/loader.js:774:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:641:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [
    ?[32m'c:\\Users\\FengTingting\\Downloads\\vue2-manage-master\\build\\webpack.prod.conf.js'?[39m,
    ?[32m'c:\\Users\\FengTingting\\Downloads\\vue2-manage-master\\build\\build.js'?[39m
  ]
}
