### ISSUE TITLE
npm run local (访问本地后台系统，需运行node-elm后台系统)

### ISSUE THREAD

**Issue by SilenceofC** [bailicangdu/vue2-manage#52]
npm run dev是好的，，，，但是到了npm run local就会出现下面这些错误
Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8002
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at Server.listen (net.js:1378:5)
    at EventEmitter.listen (E:\vue2-manage\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (E:\vue2-manage\build\dev-server.js:97:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at notFoundError (E:\vue2-manage\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (E:\vue2-manage\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (E:\vue2-manage\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "run" "local"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! vue2-manage@1.0.1 local: `cross-env NODE_ENV=local node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue2-manage@1.0.1 local script 'cross-env NODE_ENV=local node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue2-manage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=local node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue2-manage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue2-manage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vue2-manage\npm-debug.log

**Comment by bailicangdu** [comment]
后台系统启动出错了吗

**Comment by qkqkkaka** [comment]
我也是一样的错误提示
